
IMAGE = \
	key_bindings key_bindings.png\
	mouse mouse.png\
	plugins plugins.png\
	messagebox_info messagebox_info.png\
	wind_pic window.png\
	configure_pic configure.png\
	topleft top-left.png\
	top top.png\
	topright top-right.png\
	bottomleft bottom-left.png\
	bottom bottom.png\
	bottomright bottom-right.png\
	left left.png\
	centre centre.png\
	right right.png\
	confgktosd gtk-osd.png\
	keyboardim keyboard.png\
	cdaudio cdaudio.png\
	klipper_dock klipper_dock.png\
	locale_im locale.png\
	terminal terminal.png\
	vol_down vol-down.png\
	vol_mute vol-mute.png\
	vol vol.png\
	vol_up vol-up.png
	
	

all:
	gdk-pixbuf-csource --raw --static --build-list $(IMAGE) > sven_icons.h




